# Generated by Django 4.2.16 on 2024-11-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='flavor',
            field=models.CharField(max_length=50, verbose_name='Вкус мороженого'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название мороженого'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена'),
        ),
    ]
